// modules/ROOT/pages/environment.adoc
= Let’s learn about the working environment
:page-nav-title: Working Environment
:page-description: Overview of the interactive workshop environment

In this workshop, you'll have access to a comprehensive and pre-configured interactive environment, ready for you to begin working. The environment is designed to streamline each step of the InstructLab model fine-tuning process. You’ll see three primary working sections accessible through tabs in your workshop environment interface to the right:

. *Terminal (venv):* You’ll have two vertically‑stacked terminal windows, both set up with activated Python virtual environments (`venv`). This environment includes all necessary dependencies and tools, such as InstructLab, already installed and configured.
  .. *Upper Terminal:* You will use this for running & serving models with InstructLab.
  .. *Lower Terminal:* Here you’ll run commands to validate training data, kick off your synthetic data generation pipeline, and initiate fine‑tuning tasks.

. *Visual Studio Code (VSCode):* VSCode is pre‑loaded with a template folder containing an InstructLab taxonomy structure for you to add curated seed data for model training.
  .. You will find structured directories for your `qna.yaml` seed data, reflecting best practices in taxonomy‑driven data curation.
  .. VSCode’s integrated tools help you efficiently edit and validate Markdown and YAML content as you prepare your datasets.

. *404 Airlines Demo Application:* This tab displays a mock production environment for 404 Airlines.
  .. Here you’ll test and visualize interactions with the customized AI model, simulating customer service queries, airline policy questions, and operational guidance.
  .. This allows for real‑time evaluation of your fine‑tuned model’s practical effectiveness, helping you clearly see the impact and value added by domain‑specific fine‑tuning.

Throughout the workshop, you'll navigate seamlessly between these environments, following step‑by‑step instructions provided in this tutorial. For example, you may run commands in the *Upper Terminal*, add content to *VSCode*, and perform other operations as guided.
